CREATE TABLE Ticket (

ticketId int generated BY DEFAULT AS identity PRIMARY KEY,
ticketAvailable BOOLEAN DEFAULT TRUE,
entryTime timestamp DEFAULT current_timestamp NOT NULL,
exitTime timestamp,
fee float

);
